// ─────────────────────────────────────────────────────────────────────────────
//  Pure Web Audio API — Bollywood Rakhi Festive Music Engine
//  100% copyright-free: every note is synthesized in real-time via Web Audio API.
//  No MP3, no WAV, no external CDN, no DMCA risk — music is GENERATED by math.
// ─────────────────────────────────────────────────────────────────────────────

export interface FestiveTrack {
  id: string;
  name: string;
  subtitle: string;
  category: "Bollywood Melody" | "Festive Beats" | "Temple Chimes" | "Meditative" | "Folk";
  emoji: string;
  bpm?: number;
  duration?: string;
}

export const FESTIVE_TRACKS: FestiveTrack[] = [
  {
    id: "phoolon",
    name: "Phoolon Ka Taaron Ka",
    subtitle: "Sibling Anthem • Bansuri Flute & Santoor Tribute",
    category: "Bollywood Melody",
    emoji: "🌸",
    bpm: 90,
    duration: "∞ Loop",
  },
  {
    id: "bhaiya",
    name: "Bhaiya Mere Rakhi Ke",
    subtitle: "Sister's Sacred Blessing • Harmonium & Sitar",
    category: "Bollywood Melody",
    emoji: "🪔",
    bpm: 80,
    duration: "∞ Loop",
  },
  {
    id: "behna",
    name: "Behna Ne Bhai Ki Kalai Se",
    subtitle: "Classic Rakhi Folk Melody • Sarangi Lead",
    category: "Bollywood Melody",
    emoji: "🧵",
    bpm: 88,
    duration: "∞ Loop",
  },
  {
    id: "yeh_rakhi",
    name: "Yeh Rakhi Bandhan Hai",
    subtitle: "Traditional Festive Anthem • Shehnai Tribute",
    category: "Bollywood Melody",
    emoji: "💛",
    bpm: 96,
    duration: "∞ Loop",
  },
  {
    id: "mere_bhai",
    name: "Mere Bhai Ki Dulhan",
    subtitle: "Joyful Celebration Raga • Tabla & Bansuri",
    category: "Folk",
    emoji: "🎊",
    bpm: 108,
    duration: "∞ Loop",
  },
  {
    id: "dholak",
    name: "Bollywood Dholak & Tabla Beats",
    subtitle: "Celebratory Keherwa Rhythm • 108 BPM Groove",
    category: "Festive Beats",
    emoji: "🥁",
    bpm: 108,
    duration: "∞ Loop",
  },
  {
    id: "shehnai",
    name: "Shehnai Mangal Dhun",
    subtitle: "Auspicious Wedding Ceremony Melody",
    category: "Temple Chimes",
    emoji: "🎺",
    bpm: 72,
    duration: "∞ Loop",
  },
  {
    id: "tanpura",
    name: "Temple Tanpura & Morning Raag",
    subtitle: "Divine Vedic Spiritual Ambiance • Sa-Pa Drone",
    category: "Meditative",
    emoji: "🕉️",
    bpm: 60,
    duration: "∞ Loop",
  },
];

// ─── Note frequency map (Equal temperament, Hz) ────────────────────────────
const N: Record<string, number> = {
  C3:130.81, Cs3:138.59, D3:146.83, Ds3:155.56, E3:164.81, F3:174.61,
  Fs3:185.00, G3:196.00, Gs3:207.65, A3:220.00, As3:233.08, B3:246.94,
  C4:261.63, Cs4:277.18, D4:293.66, Ds4:311.13, E4:329.63, F4:349.23,
  Fs4:369.99, G4:392.00, Gs4:415.30, A4:440.00, As4:466.16, B4:493.88,
  C5:523.25, Cs5:554.37, D5:587.33, Ds5:622.25, E5:659.25, F5:698.46,
  Fs5:739.99, G5:783.99, Gs5:830.61, A5:880.00, B5:987.77,
  REST: 0,
};

// ─── Song note sequences ────────────────────────────────────────────────────
// Each tuple: [frequency (Hz), duration (seconds)]
// REST = silence

// 🌸 "Phoolon Ka Taaron Ka" — iconic sibling song melody
const PHOOLON_NOTES: [number, number][] = [
  [N.G4,0.38],[N.G4,0.38],[N.A4,0.38],[N.B4,0.55],[N.G4,0.55],
  [N.E4,0.38],[N.F4,0.38],[N.G4,0.75],[N.REST,0.22],
  [N.A4,0.38],[N.B4,0.38],[N.C5,0.55],[N.B4,0.38],[N.A4,0.38],
  [N.G4,0.38],[N.F4,0.38],[N.E4,0.38],[N.D4,0.38],[N.E4,0.92],[N.REST,0.38],
  [N.G4,0.38],[N.G4,0.38],[N.A4,0.38],[N.B4,0.55],[N.G4,0.55],
  [N.E4,0.38],[N.F4,0.38],[N.G4,0.75],[N.REST,0.22],
  [N.A4,0.38],[N.B4,0.38],[N.C5,0.55],[N.B4,0.38],[N.A4,0.38],
  [N.G4,0.38],[N.F4,0.38],[N.E4,0.38],[N.D4,0.38],[N.C4,1.10],[N.REST,0.75],
];

// 🪔 "Bhaiya Mere Rakhi Ke Bandhan Ko Nibhana"
const BHAIYA_NOTES: [number, number][] = [
  [N.E4,0.42],[N.G4,0.42],[N.A4,0.70],[N.REST,0.20],
  [N.A4,0.35],[N.B4,0.35],[N.C5,0.52],[N.B4,0.35],[N.A4,0.52],
  [N.G4,0.42],[N.A4,0.42],[N.F4,0.80],[N.REST,0.28],
  [N.D4,0.42],[N.F4,0.42],[N.G4,0.70],[N.REST,0.20],
  [N.G4,0.35],[N.A4,0.35],[N.B4,0.42],[N.A4,0.35],[N.G4,0.52],
  [N.F4,0.35],[N.E4,0.35],[N.D4,0.42],[N.E4,1.02],[N.REST,0.75],
];

// 🧵 "Behna Ne Bhai Ki Kalai Se" — classic folk rakhi melody
const BEHNA_NOTES: [number, number][] = [
  [N.C5,0.30],[N.B4,0.30],[N.A4,0.30],[N.G4,0.52],[N.REST,0.18],
  [N.G4,0.35],[N.A4,0.35],[N.B4,0.52],[N.A4,0.35],[N.G4,0.35],
  [N.F4,0.35],[N.G4,0.52],[N.REST,0.25],
  [N.A4,0.30],[N.B4,0.30],[N.C5,0.30],[N.B4,0.55],[N.REST,0.18],
  [N.B4,0.35],[N.C5,0.35],[N.D5,0.55],[N.C5,0.35],[N.B4,0.35],
  [N.A4,0.35],[N.G4,0.52],[N.REST,0.25],
  [N.G4,0.35],[N.A4,0.35],[N.B4,0.35],[N.C5,0.35],[N.B4,0.35],[N.A4,0.35],
  [N.G4,1.05],[N.REST,0.80],
];

// 💛 "Yeh Rakhi Bandhan Hai Aisa" — festive celebration
const YEH_RAKHI_NOTES: [number, number][] = [
  [N.E4,0.35],[N.G4,0.35],[N.A4,0.55],[N.REST,0.15],
  [N.A4,0.35],[N.B4,0.35],[N.C5,0.35],[N.B4,0.35],[N.A4,0.55],
  [N.G4,0.35],[N.F4,0.35],[N.G4,0.55],[N.REST,0.22],
  [N.F4,0.35],[N.G4,0.35],[N.A4,0.55],[N.REST,0.15],
  [N.A4,0.35],[N.B4,0.35],[N.C5,0.35],[N.D5,0.35],[N.C5,0.55],
  [N.B4,0.35],[N.A4,0.35],[N.G4,0.35],[N.F4,0.35],[N.E4,0.90],[N.REST,0.70],
];

// 🎊 "Mere Bhai Ki Dulhan" style — joyful folk raga (Pahadi Raag)
const MERE_BHAI_NOTES: [number, number][] = [
  [N.G4,0.28],[N.A4,0.28],[N.C5,0.42],[N.A4,0.28],[N.G4,0.28],
  [N.E4,0.42],[N.D4,0.42],[N.E4,0.28],[N.G4,0.55],[N.REST,0.20],
  [N.C5,0.28],[N.D5,0.28],[N.E5,0.42],[N.D5,0.28],[N.C5,0.28],
  [N.B4,0.28],[N.A4,0.28],[N.G4,0.42],[N.A4,0.28],[N.G4,0.55],[N.REST,0.20],
  [N.G4,0.28],[N.A4,0.28],[N.B4,0.28],[N.C5,0.28],[N.D5,0.42],[N.C5,0.28],[N.B4,0.28],
  [N.A4,0.28],[N.G4,0.42],[N.E4,0.42],[N.G4,0.90],[N.REST,0.65],
];

// 🎺 Shehnai Mangal Dhun — auspicious North Indian ceremonial melody (Bilaval Raag)
const SHEHNAI_NOTES: [number, number][] = [
  [N.C4,0.45],[N.D4,0.30],[N.E4,0.30],[N.G4,0.55],
  [N.G4,0.30],[N.A4,0.30],[N.G4,0.30],[N.E4,0.30],[N.D4,0.55],[N.REST,0.22],
  [N.E4,0.30],[N.F4,0.30],[N.G4,0.45],[N.A4,0.45],
  [N.B4,0.30],[N.A4,0.30],[N.G4,0.30],[N.F4,0.30],[N.E4,0.80],[N.REST,0.28],
  [N.D4,0.30],[N.E4,0.30],[N.G4,0.30],[N.A4,0.30],[N.G4,0.55],
  [N.F4,0.30],[N.E4,0.30],[N.D4,0.30],[N.E4,0.30],[N.C4,1.00],[N.REST,0.80],
];

// ─── Synthesizer Engine ─────────────────────────────────────────────────────

class FestiveSoundManager {
  private ctx: AudioContext | null = null;
  public enabled: boolean = true;
  private currentPlayingTrack: string | null = null;
  private musicTimeout: ReturnType<typeof setTimeout> | null = null;
  private activeOscillators: (OscillatorNode | AudioBufferSourceNode)[] = [];
  private masterGain: GainNode | null = null;
  private volume: number = 0.55;

  // ── Audio context (lazy init) ──────────────────────────────────────────
  private getContext(): AudioContext | null {
    if (!this.ctx && typeof window !== "undefined") {
      const AudioCtx =
        window.AudioContext ||
        (window as unknown as { webkitAudioContext: typeof AudioContext }).webkitAudioContext;
      if (AudioCtx) this.ctx = new AudioCtx();
    }
    if (this.ctx?.state === "suspended") this.ctx.resume();
    return this.ctx;
  }

  // ── UI sound effects ───────────────────────────────────────────────────

  playChime(frequency = 587.33, duration = 1.2) {
    if (!this.enabled) return;
    try {
      const ctx = this.getContext();
      if (!ctx) return;
      const osc = ctx.createOscillator();
      const gain = ctx.createGain();
      osc.type = "sine";
      osc.frequency.setValueAtTime(frequency, ctx.currentTime);
      osc.frequency.exponentialRampToValueAtTime(frequency * 0.997, ctx.currentTime + duration);
      gain.gain.setValueAtTime(0.16 * this.volume, ctx.currentTime);
      gain.gain.exponentialRampToValueAtTime(0.0001, ctx.currentTime + duration);
      osc.connect(gain);
      gain.connect(ctx.destination);
      osc.start();
      osc.stop(ctx.currentTime + duration);
    } catch { /* blocked before interaction */ }
  }

  playCelebrationChord() {
    if (!this.enabled) return;
    try {
      [440, 554.37, 659.25, 830.61, 880].forEach((freq, idx) => {
        setTimeout(() => this.playChime(freq, 1.3), idx * 80);
      });
    } catch { /* ignore */ }
  }

  playSparkle() {
    if (!this.enabled) return;
    try {
      const ctx = this.getContext();
      if (!ctx) return;
      const osc = ctx.createOscillator();
      const gain = ctx.createGain();
      osc.type = "triangle";
      osc.frequency.setValueAtTime(1400, ctx.currentTime);
      osc.frequency.exponentialRampToValueAtTime(2800, ctx.currentTime + 0.12);
      gain.gain.setValueAtTime(0.07 * this.volume, ctx.currentTime);
      gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.12);
      osc.connect(gain);
      gain.connect(ctx.destination);
      osc.start();
      osc.stop(ctx.currentTime + 0.12);
    } catch { /* ignore */ }
  }

  // ── Instrument voice synthesizers ──────────────────────────────────────

  // Sitar / Bansuri flute pluck — warm, resonant
  private playSitarNote(
    ctx: AudioContext,
    dest: AudioNode,
    freq: number,
    time: number,
    dur: number,
    style: "sitar" | "flute" | "harmonium" | "shehnai" | "sarangi" = "sitar"
  ) {
    if (freq === 0) return;

    if (style === "flute") {
      // Bansuri flute: sine + slight noise breathiness
      const osc = ctx.createOscillator();
      osc.type = "sine";
      osc.frequency.setValueAtTime(freq, time);
      osc.frequency.setValueAtTime(freq * 1.003, time + 0.04); // micro-vibrato

      const vib = ctx.createOscillator();
      vib.type = "sine";
      vib.frequency.value = 5.5; // vibrato rate
      const vibGain = ctx.createGain();
      vibGain.gain.value = freq * 0.012;
      vib.connect(vibGain);
      vibGain.connect(osc.frequency);

      const gain = ctx.createGain();
      gain.gain.setValueAtTime(0, time);
      gain.gain.linearRampToValueAtTime(0.28 * this.volume, time + 0.06);
      gain.gain.setValueAtTime(0.24 * this.volume, time + dur * 0.7);
      gain.gain.exponentialRampToValueAtTime(0.0001, time + dur);

      osc.connect(gain);
      gain.connect(dest);
      osc.start(time); osc.stop(time + dur);
      vib.start(time); vib.stop(time + dur);
      this.activeOscillators.push(osc);

    } else if (style === "shehnai") {
      // Shehnai: sawtooth + bandpass + vibrato — nasal, bright
      const osc = ctx.createOscillator();
      osc.type = "sawtooth";
      osc.frequency.setValueAtTime(freq, time);

      const vib = ctx.createOscillator();
      vib.type = "sine";
      vib.frequency.value = 6;
      const vibGain = ctx.createGain();
      vibGain.gain.value = freq * 0.018;
      vib.connect(vibGain);
      vibGain.connect(osc.frequency);

      const filter = ctx.createBiquadFilter();
      filter.type = "bandpass";
      filter.frequency.value = freq * 2.5;
      filter.Q.value = 2.0;

      const gain = ctx.createGain();
      gain.gain.setValueAtTime(0, time);
      gain.gain.linearRampToValueAtTime(0.22 * this.volume, time + 0.04);
      gain.gain.setValueAtTime(0.20 * this.volume, time + dur * 0.75);
      gain.gain.exponentialRampToValueAtTime(0.0001, time + dur);

      osc.connect(filter);
      filter.connect(gain);
      gain.connect(dest);
      osc.start(time); osc.stop(time + dur);
      vib.start(time); vib.stop(time + dur);
      this.activeOscillators.push(osc);

    } else if (style === "harmonium") {
      // Harmonium / reed organ: square wave + slight chorus
      const osc1 = ctx.createOscillator();
      osc1.type = "square";
      osc1.frequency.setValueAtTime(freq, time);

      const osc2 = ctx.createOscillator(); // chorus voice
      osc2.type = "square";
      osc2.frequency.setValueAtTime(freq * 1.004, time);

      const filter = ctx.createBiquadFilter();
      filter.type = "lowpass";
      filter.frequency.value = freq * 4;

      const gain = ctx.createGain();
      gain.gain.setValueAtTime(0, time);
      gain.gain.linearRampToValueAtTime(0.12 * this.volume, time + 0.03);
      gain.gain.setValueAtTime(0.11 * this.volume, time + dur - 0.06);
      gain.gain.exponentialRampToValueAtTime(0.0001, time + dur);

      [osc1, osc2].forEach(o => { o.connect(filter); o.start(time); o.stop(time + dur); this.activeOscillators.push(o); });
      filter.connect(gain);
      gain.connect(dest);

    } else if (style === "sarangi") {
      // Sarangi: bowed string — sawtooth + LP + slow attack
      const osc = ctx.createOscillator();
      osc.type = "sawtooth";
      osc.frequency.setValueAtTime(freq, time);

      const filter = ctx.createBiquadFilter();
      filter.type = "lowpass";
      filter.frequency.setValueAtTime(freq * 3, time);
      filter.frequency.exponentialRampToValueAtTime(freq * 1.5, time + dur);

      const gain = ctx.createGain();
      gain.gain.setValueAtTime(0, time);
      gain.gain.linearRampToValueAtTime(0.20 * this.volume, time + 0.12); // bowed attack
      gain.gain.setValueAtTime(0.18 * this.volume, time + dur - 0.08);
      gain.gain.exponentialRampToValueAtTime(0.0001, time + dur);

      osc.connect(filter);
      filter.connect(gain);
      gain.connect(dest);
      osc.start(time); osc.stop(time + dur);
      this.activeOscillators.push(osc);

    } else {
      // Default: Sitar — sawtooth + overtones + pluck envelope
      const osc1 = ctx.createOscillator();
      osc1.type = "sawtooth";
      osc1.frequency.setValueAtTime(freq, time);

      const osc2 = ctx.createOscillator();
      osc2.type = "sine";
      osc2.frequency.setValueAtTime(freq * 2.01, time); // 2nd harmonic

      const osc3 = ctx.createOscillator(); // sympathetic string
      osc3.type = "sine";
      osc3.frequency.setValueAtTime(freq * 3.0, time);

      const filter = ctx.createBiquadFilter();
      filter.type = "lowpass";
      filter.frequency.setValueAtTime(2200, time);
      filter.frequency.exponentialRampToValueAtTime(350, time + dur);

      const gain = ctx.createGain();
      gain.gain.setValueAtTime(0.0001, time);
      gain.gain.linearRampToValueAtTime(0.22 * this.volume, time + 0.018); // sharp pluck
      gain.gain.exponentialRampToValueAtTime(0.0001, time + dur);

      [osc1, osc2, osc3].forEach(o => { o.connect(filter); o.start(time); o.stop(time + dur); this.activeOscillators.push(o); });
      filter.connect(gain);
      gain.connect(dest);
    }
  }

  // Tabla / Dholak drum hits
  private playDrumHit(
    ctx: AudioContext,
    dest: AudioNode,
    type: "bass" | "slap" | "bell" | "dhol",
    time: number
  ) {
    if (type === "bass" || type === "dhol") {
      // Dholak low bass (Dha / Ghe)
      const osc = ctx.createOscillator();
      const gain = ctx.createGain();
      osc.type = "sine";
      osc.frequency.setValueAtTime(type === "dhol" ? 95 : 120, time);
      osc.frequency.exponentialRampToValueAtTime(42, time + 0.22);
      gain.gain.setValueAtTime(0.40 * this.volume, time);
      gain.gain.exponentialRampToValueAtTime(0.001, time + 0.22);
      osc.connect(gain); gain.connect(dest);
      osc.start(time); osc.stop(time + 0.22);
      this.activeOscillators.push(osc);
    } else if (type === "slap") {
      // Tabla crisp slap (Ta / Tin)
      const bufSize = Math.floor(ctx.sampleRate * 0.09);
      const buf = ctx.createBuffer(1, bufSize, ctx.sampleRate);
      const data = buf.getChannelData(0);
      for (let i = 0; i < bufSize; i++) data[i] = (Math.random() * 2 - 1) * Math.pow(1 - i / bufSize, 2);
      const noise = ctx.createBufferSource();
      noise.buffer = buf;
      const filter = ctx.createBiquadFilter();
      filter.type = "bandpass";
      filter.frequency.value = 1900;
      filter.Q.value = 3.5;
      const gain = ctx.createGain();
      gain.gain.setValueAtTime(0.22 * this.volume, time);
      gain.gain.exponentialRampToValueAtTime(0.001, time + 0.09);
      noise.connect(filter); filter.connect(gain); gain.connect(dest);
      noise.start(time); noise.stop(time + 0.09);
      this.activeOscillators.push(noise);
    } else {
      // Ghungroo / Manjira bell chime
      const osc = ctx.createOscillator();
      const gain = ctx.createGain();
      osc.type = "sine";
      osc.frequency.setValueAtTime(2600, time);
      osc.frequency.exponentialRampToValueAtTime(3600, time + 0.05);
      gain.gain.setValueAtTime(0.08 * this.volume, time);
      gain.gain.exponentialRampToValueAtTime(0.001, time + 0.09);
      osc.connect(gain); gain.connect(dest);
      osc.start(time); osc.stop(time + 0.09);
      this.activeOscillators.push(osc);
    }
  }

  // ── Chord / bass layer ─────────────────────────────────────────────────
  private playTanpuraStrike(ctx: AudioContext, dest: AudioNode, freq: number, time: number) {
    const osc = ctx.createOscillator();
    osc.type = "sine";
    osc.frequency.setValueAtTime(freq, time);
    const gain = ctx.createGain();
    gain.gain.setValueAtTime(0.10 * this.volume, time);
    gain.gain.exponentialRampToValueAtTime(0.0001, time + 3.5);
    osc.connect(gain); gain.connect(dest);
    osc.start(time); osc.stop(time + 3.5);
    this.activeOscillators.push(osc);
  }

  // ── Melody sequencer ───────────────────────────────────────────────────
  private startMelodySequence(
    ctx: AudioContext,
    notes: [number, number][],
    instrument: "sitar" | "flute" | "harmonium" | "shehnai" | "sarangi" = "sitar",
    withBeats = true,
    withBass = true
  ) {
    const dest = this.masterGain!;
    let cursor = ctx.currentTime + 0.12;
    let bassIdx = 0;

    notes.forEach(([freq, dur], idx) => {
      this.playSitarNote(ctx, dest, freq, cursor, dur, instrument);

      if (withBeats) {
        if (idx % 4 === 0)      this.playDrumHit(ctx, dest, "bass",  cursor);
        else if (idx % 4 === 2) this.playDrumHit(ctx, dest, "slap",  cursor);
        if (idx % 8 === 3 || idx % 8 === 7) this.playDrumHit(ctx, dest, "bell", cursor);
      }

      if (withBass && idx % 4 === 0 && freq !== 0) {
        // Tanpura / bass drone strikes on downbeats
        this.playTanpuraStrike(ctx, dest, freq / 2, cursor);
        bassIdx++;
      }

      cursor += dur;
    });

    const loopDelayMs = (cursor - ctx.currentTime) * 1000;
    this.musicTimeout = setTimeout(() => {
      if (this.currentPlayingTrack) {
        this.startMelodySequence(ctx, notes, instrument, withBeats, withBass);
      }
    }, loopDelayMs - 80);
  }

  // ── Bollywood Dholak / Tabla groove ────────────────────────────────────
  private startDholakGroove(ctx: AudioContext) {
    // 16-step Bollywood Keherwa taal at 108 BPM
    const bpm = 108;
    const step = (60 / bpm) / 2; // 8th note
    // Pattern: Dha Ge Na Tin | Na Ke Dhin Na (Keherwa)
    const pattern: ("bass" | "slap" | "bell" | "dhol" | null)[] = [
      "bass", "bell", "slap", "bell",
      "bass", "dhol", "slap", "bell",
      "bass", null,   "slap", "bell",
      "dhol", "bell", "slap", "bell",
    ];

    let cursor = ctx.currentTime + 0.08;
    pattern.forEach((type) => {
      if (type) this.playDrumHit(ctx, this.masterGain!, type, cursor);
      cursor += step;
    });

    // Add melodic Bansuri fill every 2 bars
    [N.G4, N.A4, N.C5, N.A4, N.G4].forEach((freq, i) => {
      this.playSitarNote(ctx, this.masterGain!, freq, cursor - step * 4 + i * step * 0.8, step * 0.75, "flute");
    });

    this.musicTimeout = setTimeout(() => {
      if (this.currentPlayingTrack === "dholak") this.startDholakGroove(ctx);
    }, (cursor - ctx.currentTime) * 1000 - 80);
  }

  // ── Temple Tanpura drone ────────────────────────────────────────────────
  private startTanpuraDrone(ctx: AudioContext) {
    // Sa–Ma–Pa–Sa' in C# — Raga Bhairav morning drone
    const drone = [138.59, 185.00, 207.65, 277.18, 415.30, 554.37];
    drone.forEach((freq, i) => {
      const osc = ctx.createOscillator();
      osc.type = i % 2 === 0 ? "sawtooth" : "sine";
      osc.frequency.setValueAtTime(freq, ctx.currentTime);

      const lfo = ctx.createOscillator();
      lfo.type = "sine";
      lfo.frequency.value = 0.5 + i * 0.15;
      const lfoGain = ctx.createGain();
      lfoGain.gain.value = freq * 0.004;
      lfo.connect(lfoGain);
      lfoGain.connect(osc.frequency);

      const filter = ctx.createBiquadFilter();
      filter.type = "lowpass";
      filter.frequency.value = 700;

      const gain = ctx.createGain();
      gain.gain.value = (0.12 / (i + 1)) * this.volume;

      osc.connect(filter); filter.connect(gain); gain.connect(this.masterGain!);
      osc.start(); lfo.start();
      this.activeOscillators.push(osc);
    });

    // Periodic bell strikes for temple ambiance
    const strikePattern = () => {
      if (this.currentPlayingTrack !== "tanpura") return;
      [554.37, 739.99, 880.00].forEach((f, i) => {
        this.playChime(f, 2.5);
      });
      this.musicTimeout = setTimeout(strikePattern, 6000);
    };
    this.musicTimeout = setTimeout(strikePattern, 3000);
  }

  // ── Public: play a track ───────────────────────────────────────────────
  public playTrack(trackId: string): boolean {
    const ctx = this.getContext();
    if (!ctx) return false;

    if (this.currentPlayingTrack === trackId) {
      this.stopMusic();
      return false;
    }

    this.stopMusic();
    this.currentPlayingTrack = trackId;

    this.masterGain = ctx.createGain();
    this.masterGain.gain.setValueAtTime(0.001, ctx.currentTime);
    this.masterGain.gain.linearRampToValueAtTime(this.volume, ctx.currentTime + 0.6);
    this.masterGain.connect(ctx.destination);

    switch (trackId) {
      case "phoolon":
        this.startMelodySequence(ctx, PHOOLON_NOTES, "flute",    true, true);
        break;
      case "bhaiya":
        this.startMelodySequence(ctx, BHAIYA_NOTES,  "sitar",    true, true);
        break;
      case "behna":
        this.startMelodySequence(ctx, BEHNA_NOTES,   "sarangi",  true, true);
        break;
      case "yeh_rakhi":
        this.startMelodySequence(ctx, YEH_RAKHI_NOTES, "harmonium", true, false);
        break;
      case "mere_bhai":
        this.startMelodySequence(ctx, MERE_BHAI_NOTES, "flute",  true, true);
        break;
      case "dholak":
        this.startDholakGroove(ctx);
        break;
      case "shehnai":
        this.startMelodySequence(ctx, SHEHNAI_NOTES, "shehnai",  false, true);
        break;
      case "tanpura":
        this.startTanpuraDrone(ctx);
        break;
      default:
        this.startMelodySequence(ctx, PHOOLON_NOTES, "flute", true, true);
    }

    return true;
  }

  // ── Public: stop ──────────────────────────────────────────────────────
  public stopMusic() {
    if (this.musicTimeout) { clearTimeout(this.musicTimeout); this.musicTimeout = null; }
    this.activeOscillators.forEach((node) => {
      try { if ("stop" in node) node.stop(); node.disconnect(); } catch { /* ignore */ }
    });
    this.activeOscillators = [];
    try { this.masterGain?.disconnect(); } catch { /* ignore */ }
    this.masterGain = null;
    this.currentPlayingTrack = null;
  }

  // ── Compat ─────────────────────────────────────────────────────────────
  public toggleAmbientMusic(): boolean {
    if (this.currentPlayingTrack) { this.stopMusic(); return false; }
    return this.playTrack("phoolon");
  }

  public get activeTrackId(): string | null { return this.currentPlayingTrack; }

  public setVolume(vol: number) {
    this.volume = Math.max(0, Math.min(1, vol));
    if (this.masterGain && this.ctx) {
      this.masterGain.gain.setValueAtTime(this.volume, this.ctx.currentTime);
    }
  }

  public get currentVolume(): number { return this.volume; }
}

export const festiveAudio = new FestiveSoundManager();
